import {searchItems} from './search.js';import {card,bindCards,updateFavoriteCount} from './ui.js';import {getFavorites} from './favorites.js';
const categories=['Face Masks','Masks','Helms','Horns','Hairs','Wings','Capes','Armor','Weapons','Swords','Daggers','Axes','Staffs','Pets','Back Items','Shoulder Items','Effects','Miscellaneous'];let items=[];
const plural=s=>s==='Armor'?'Armor':s;
function categoryCards(target,limit){if(!target)return;target.innerHTML=categories.slice(0,limit||categories.length).map(c=>`<a class="category-card" href="items.html?q=${encodeURIComponent(c)}"><strong>${c}</strong><span>Browse matching items →</span></a>`).join('')}
function unique(field){return [...new Set(items.map(i=>i[field]).filter(Boolean))].sort()}
function addOptions(id,values){const select=document.querySelector(id);if(select)select.insertAdjacentHTML('beforeend',values.map(v=>`<option value="${v}">${v}</option>`).join(''))}
function debounce(fn,wait=200){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),wait)}}
function initItems(){const query=new URLSearchParams(location.search).get('q')||'';const input=document.querySelector('#searchInput');input.value=query;addOptions('#typeFilter',unique('type'));addOptions('#categoryFilter',unique('category'));addOptions('#rarityFilter',unique('rarity'));let visible=15;const render=()=>{let found=searchItems(items,input.value);const type=document.querySelector('#typeFilter').value,cat=document.querySelector('#categoryFilter').value,rar=document.querySelector('#rarityFilter').value,member=document.querySelector('#memberFilter').value,ac=document.querySelector('#acFilter').checked;found=found.filter(({item})=>(!type||item.type===type)&&(!cat||item.category===cat)&&(!rar||item.rarity===rar)&&(!member||item.member===member)&&(!ac||item.ac));const sort=document.querySelector('#sortSelect').value;const rarityOrder={Common:1,Rare:2,Awesome:3,'Ultra Rare':4,Legendary:5};found.sort((a,b)=>sort==='az'?a.item.name.localeCompare(b.item.name):sort==='za'?b.item.name.localeCompare(a.item.name):sort==='newest'?b.item.year-a.item.year:sort==='oldest'?a.item.year-b.item.year:sort==='rarity'?(rarityOrder[b.item.rarity]||0)-(rarityOrder[a.item.rarity]||0):sort==='id'?a.item.id-b.item.id:b.score-a.score);document.querySelector('#resultCount').textContent=`${found.length} ${input.value?`matching “${input.value}” `:''}item${found.length===1?'':'s'} found`;document.querySelector('#itemGrid').innerHTML=found.slice(0,visible).map(x=>card(x.item)).join('')||'<p class="empty">No items match those filters. Try a broader tag or clear filters.</p>';bindCards(items);const more=document.querySelector('#loadMore');more.hidden=found.length<=visible;more.onclick=()=>{visible+=15;render()}};document.querySelectorAll('.filters select,.filters input,#sortSelect').forEach(e=>e.onchange=()=>{visible=15;render()});input.addEventListener('input',debounce(()=>{visible=15;render()}));input.closest('form').onsubmit=e=>{e.preventDefault();visible=15;render()};document.querySelector('#clearFilters').onclick=()=>{document.querySelectorAll('.filters select').forEach(x=>x.value='');document.querySelector('#acFilter').checked=false;render()};render()}
function initFavorites(){const saved=new Set(getFavorites());const selected=items.filter(i=>saved.has(i.id));document.querySelector('#favoritesIntro').textContent=selected.length?`${selected.length} saved item${selected.length===1?'':'s'} on this device.`:'No favorites yet—find an item and tap the heart to save it here.';document.querySelector('#favoritesGrid').innerHTML=selected.map(card).join('');bindCards(items)}
async function init(){updateFavoriteCount();try{items=await fetch('data/items.json').then(r=>{if(!r.ok)throw Error();return r.json()})}catch{document.querySelector('main').insertAdjacentHTML('afterbegin','<p class="data-error">Could not load sample data. Open the site through a local web server (such as VS Code Live Server).</p>');return}categoryCards(document.querySelector('#featuredCategories'),6);categoryCards(document.querySelector('#categoryGrid'));const feature=document.querySelector('#featuredItems');if(feature){feature.innerHTML=items.slice(0,5).map(card).join('');bindCards(items)}if(document.querySelector('#itemGrid'))initItems();if(document.querySelector('#favoritesGrid'))initFavorites()}init();
